### ISSUE TITLE
Trainer names

### ISSUE THREAD

**Issue by BrokenR3C0RD** [pret/pokeyellow#20]
I'm working on a ROM hack using the disassembled code here as a base. I want to edit some trainer names (e.g., Misty, Jessie & James, etc), however, running a grep recursive search shows nothing useful. Has that part of the binary not been disassembled yet? If not, where in the tree are they stored?

**Comment by dannye** [comment]
The entire binary has been disassembled

Trainer names are in text/trainer_names.asm

**Comment by BrokenR3C0RD** [comment]
I only see trainer classes and 1 or 2 trainers, but no trainer names. For example, I can't find the name of "GIOVANNI" anywhere

**Comment by BrokenR3C0RD** [comment]
What about JESSIE and JAMES?

**Comment by dannye** [comment]
To clarify, Pokemon Yellow never refers to as Jessie and James as Jessie and James. They are simply referred to as ROCKET.

https://s19.postimg.org/umjxlzxf3/Pokemon_Yellow_27.png

**Comment by BrokenR3C0RD** [comment]
I feel dumb 0_0
Sorry for such a stupid issue

**Comment by dannye** [comment]
The Jessie and James trainers share the trainer class with Rocket.
"Normal" Rockets are Rockets $01 through $29. Jessie and James are Rockets $2a through $2d (in data/trainer_parties.asm)
There are four unused Jessie and James Rockets which are numbers $2e through $31.
Rockets $2a through $31 are assigned the Jessie and James battle pic in the routine named IsFightingJessieJames: in home.asm

**Comment by BrokenR3C0RD** [comment]
Just so I don't clunk up issues, I'll ask this question here: What format are the maps in, and how can I edit them?

**Comment by dannye** [comment]
The maps are just a series of bytes which correspond to block IDs. Block IDs belong to particular tile sets. Block sets and tile sets are in gfx/blocksets/ and gfx/tilesets/.

Tile sets are literal graphics, made of tiles, which are 8x8 pixels.

Block sets are the arrangement of tiles that form blocks. Blocks are 4x4 tiles.
So each block in a block set is 16 bytes for the 16 tile IDs that make up that block, left to right and top to bottom.

**Comment by dannye** [comment]
I don't know the status of the recommended way to edit maps while using the disassembly. I don't want to misspeak.

Maybe @yenatch can give you the most up-to-date information.
