### ISSUE TITLE
audio missing?

### ISSUE THREAD

**Issue by m99900** [pret/pokeyellow#24]
rgbasm -h -o audio.o audio.asm
make: rgbasm: Command not found
make: *** [Makefile:42: audio.o] Error 127

**Comment by BrokenR3C0RD** [comment]
You don't have rgbasm installed. You need to look at the build instructions first.

**Comment by m99900** [comment]
thanks, I did download but I forgot to unpack I was able to make the player play as oak so thanks for making this!!
