### ISSUE TITLE
Errors in wram.asm

### ISSUE THREAD

**Issue by mddrill** [pret/pokeyellow#37]
Upon running `make` in the repo (after following the steps in INSTALL.md for Mac OS), I get this:

> rgbasm -h -o audio.o audio.asm
> rgbasm -h -o main.o main.asm
> rgbasm -h -o text.o text.asm
> rgbasm -h -o wram.o wram.asm
> ERROR:	wram.asm(2857) :
> 	'UNION' already defined
> ERROR:	wram.asm(2875) :
> 	'NEXTU' already defined
> ERROR:	wram.asm(2896) :
> 	'ENDU' already defined
> ERROR:	wram.asm(3504) :
> 	'UNION' already defined
> ERROR:	wram.asm(3509) :
> 	'NEXTU' already defined
> ERROR:	wram.asm(3522) :
> 	'ENDU' already defined
> rgbasm: Assembly aborted in pass 1 (6 errors)!
> make: *** [wram.o] Error 1

As I said, I am on mac.

**Comment by Rangi42** [comment]
Update rgbds to the latest version, 0.3.6.

**Comment by mddrill** [comment]
Thank you
