### ISSUE TITLE
Messed up title screen

### ISSUE THREAD

**Issue by ASDFgamer101** [pret/pokeyellow#38]
The Pokemon logo on the title screen is all messed up and looks... corrupted. Any advice?

**Comment by dannye** [comment]
What are you referring to? Do you mean the vanilla repository builds a rom which gives you a corrupted title screen? If that's the case, you must have something wrong with your setup.

Or do you mean you are making a mod and the title screen has become corrupted and you're asking how to fix it? If that's the case, I can't help without knowing more about the changes you have made.

**Comment by dannye** [comment]
Since this isn't an issue with our repo, I'm gonna close this issue

If you need help working on a mod, feel free to reach out to any of us on Discord
