### ISSUE TITLE
gfx files outside of gfx subfolders fail to get converted to .2bpp when edited

### ISSUE THREAD

**Issue by JG-GIT** [pret/pokeyellow#42]
This is constantly happening.
It has to do with a minimum of 8-bits in bit depth, even though there's only 4 colors used in the input.
"rgbgfx  -o gfx/yellow_titlescreen.2bpp gfx/yellow_titlescreen.png
error: Too many colors in input PNG file's palette to fit into a 2-bit palette (256 in input palette, max 4).
make: *** [Makefile:80: gfx/yellow_titlescreen.2bpp] Error 1"

**Comment by JG-GIT** [comment]
And when I tried manual conversion, **what.**
![what](https://user-images.githubusercontent.com/39865752/62175953-ca79e680-b2fc-11e9-9980-9ad475ac99eb.PNG)

**Comment by JG-GIT** [comment]
I actually need help with fixing this.

**Comment by dannye** [comment]
Closing as not an issue with the project. Feel free to join the discord to ask for help with things like this.
