### ISSUE TITLE
Fix the off-by-one error in pcm.py (and rewrite as pcm.c)

### ISSUE THREAD

**Issue by huderlem** [pret/pokeyellow#5]
pret can now convert .wav files to 1-bit pcm data at compile time.

First, use pret/pokemontools/pcm.py to convert all of the pikachu cries' pcm data into .wav files.  Then, INCBIN those .wav files in pokeyellow's source code.  Finally, update the MakeFile to convert .wav files to .pcm files.

Use this pokepinball commit as reference: https://github.com/pret/pokepinball/commit/10b87f178bae5c25a9926b7b6115e2caa7f2a461

**Comment by huderlem** [comment]
The following commit resolved this issue:  https://github.com/pret/pokeyellow/commit/38537b052b24e58fc7ef8823487d7e520f7e4c09

Next step would be to add a flag to pcm.py to reproduce the off-by-one error where the routine that plays the pcm data doesn't process the last byte.  Look at the PikachuCry data, and you'll see that there is an unused byte hardcoded after all of the pcm data.

**Comment by Rangi42** [comment]
While anyone's fixing the off-by-one error, rewriting it in C would also be nice.
