### ISSUE TITLE
Can't add new moves.

### ISSUE THREAD

**Issue by Pipilson** [pret/pokeyellow#77]
I wanted to add 25 new moves to the game, so I was following the Heart Stamp tutorial and to follow it I tried adding the move Signal Beam. I'm pretty sure I did everything correctly but when i try to build the room I get 3 error messages and they all points to "macros/asserts.asm::assert_table_length<16>:"

If i'm not mistaken the error message is talking about this line: "{CURRENT_TABLE_START}: expected {d:x} entries, each {d:CURRENT_TABLE_WIDTH} bytes".

I got something similar before when I tried to change some pokémon names... I'm not really sure whats going on, I guess the rom is running out of space? How can I fix this or how could I provide more info about this issue?

**Comment by Rangi42** [comment]
This is not an issue with pokeyellow, but with custom usage of it. Feel free to ask for help in the Discord `#pokered` channel.
