### ISSUE TITLE
rgbgfx not installing properly

### ISSUE THREAD

**Issue by Skyde72** [pret/pokeyellow#82]
I followed the rgbds setup guide, installed all the required libs for rgbgfx to work but it doesn't
Logs

rgbgfx  -o gfx/surfing_pikachu/surfing_pikachu_1a.2bpp gfx/surfing_pikachu/surfing_pikachu_1a.png
make: rgbgfx: Command not found
make: *** [Makefile:166: gfx/surfing_pikachu/surfing_pikachu_1a.2bpp] Error 127

Thanks
Skyde

**Comment by Rangi42** [comment]
GitHub issues are for issues with pokered itself. For technical support, try the Discord server linked in the README.
